spring.application.name=demo

spring.profiles.active=dev

# URL de conexión a tu base de datos (por defecto Postgres usa el puerto 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/market-app-26.2

# Tus credenciales de PostgreSQL
spring.datasource.username=postgres 
spring.datasource.password=carlito17.

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# MUY IMPORTANTE: Como ya tienes tablas y datos creados (tus INSERTS de la imagen),
# le decimos a Hibernate que NO modifique ni borre la estructura de tu base de datos.
spring.jpa.hibernate.ddl-auto=none

# Opcional: Para ver en consola las consultas SQL que hace Spring Boot
spring.jpa.show-sql=true